name: Keep Alive

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping ioriocars.it
        run: curl -s https://www.ioriocars.it/ > /dev/null
